name: Build and Push Docker Image to ACR

on:
  push:
    branches: [ main ]  # Trigger on push to main branch

permissions:
  id-token: write
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      ACR_LOGIN_SERVER: ${{ secrets.ACR_NAME }}.azurecr.io
      IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
      BUILD_ID: ${{ github.run_number }}
      

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        auth-type: SERVICE_PRINCIPAL

    - name: ACR Login
      run: az acr login --name ${{ secrets.ACR_NAME }}

    - name: Build Docker Image with Build ID
      run: |
        docker build -t $ACR_LOGIN_SERVER/$IMAGE_NAME:latest \
                     -t $ACR_LOGIN_SERVER/$IMAGE_NAME:build-${BUILD_ID} .

    - name: Push Docker Images to ACR
      run: |
        docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:latest
        docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:build-${BUILD_ID}
    #deploy to AKS
    - name: Trigger Deploy to AKS
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: deploy-to-aks.yml
        ref: main
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        inputs: '{"build_id":"${{ github.run_number }}"}'
