name: Build and Push Docker Image to ACR

on:
  push:
    branches: [ main ]  # Trigger on push to main branch
    
permissions:
  id-token: write
  contents: read


jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      ACR_LOGIN_SERVER: ${{ secrets.ACR_NAME }}.azurecr.io
      IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
      BUILD_ID: ${{ github.run_number }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: ACR Login
      run: az acr login --name ${{ secrets.ACR_NAME }}

    - name: Build Docker Image with Build ID
      run: |
        docker build -t $ACR_LOGIN_SERVER/$IMAGE_NAME:latest \
                     -t $ACR_LOGIN_SERVER/$IMAGE_NAME:build-${BUILD_ID} .

    - name: Push Docker Images to ACR
      run: |
        docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:latest
        docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:build-${BUILD_ID}
